"""empty message

Revision ID: 1271429731e7
Revises: 2e7f50426ccf
Create Date: 2018-03-16 14:31:17.247623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '1271429731e7'
down_revision = '2e7f50426ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('term', sa.Column('date_created', sa.DateTime()))
    op.drop_column('term', 'created_date')
    op.add_column('translation', sa.Column('date_created', sa.DateTime()))
    op.drop_column('translation', 'created_date')
    op.add_column('user', sa.Column('date_created', sa.DateTime()))
    op.drop_column('user', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user', 'date_created')
    op.add_column('translation', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('translation', 'date_created')
    op.add_column('term', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('term', 'date_created')
    # ### end Alembic commands ###
