"""empty message

Revision ID: 37febd04b687
Revises: 87bb798bbd1b
Create Date: 2018-03-03 18:25:48.109872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37febd04b687'
down_revision = '87bb798bbd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.String(length=50), nullable=True))
    #op.drop_column('user', 'is_admin')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###
