"""empty message

Revision ID: 4354b8fb64b7
Revises: bf0a5ade91ee
Create Date: 2018-05-08 23:08:16.439459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4354b8fb64b7'
down_revision = 'bf0a5ade91ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user', 'is_active')
    op.alter_column('translation', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
