"""empty message

Revision ID: 85c972b3049e
Revises: 16a51dbc5260
Create Date: 2018-03-12 11:07:19.150671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c972b3049e'
down_revision = '16a51dbc5260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('translation_translation_key', 'translation', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('translation_translation_key', 'translation', ['translation'])
    # ### end Alembic commands ###
