"""empty message

Revision ID: a2f5a0132bde
Revises: 85c972b3049e
Create Date: 2018-03-12 11:12:10.657048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f5a0132bde'
down_revision = '85c972b3049e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('term', sa.Column('full_term', sa.String(length=150), nullable=True))
    op.add_column('term', sa.Column('is_acronym', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('term', 'is_acronym')
    op.drop_column('term', 'full_term')
    # ### end Alembic commands ###
